# Generated by Django 4.0.4 on 2024-04-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.BigIntegerField(default=0),
        ),
    ]
