# Generated by Django 4.0.4 on 2024-04-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sales',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
