# Generated by Django 4.0.4 on 2024-04-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sales',
            field=models.BigIntegerField(default=0),
        ),
    ]
